#!/bin/bash

SHELL := /bin/bash

build:
	echo "make build NOT IMPLEMENTED"

push:
	echo "make push NOT IMPLEMENTED"

install:
	python setup.py install

release:
	echo "make release NOT IMPLEMENTED"

clean-pyc:
	find . -name "*.pyc" -delete
	find . -name "*.pyo" -delete
	find . -name '*~' -delete

clean-build:
	echo "make clean-build NOT IMPLEMENTED"

uninstall:
	echo "make uninstall NOT IMPLEMENTED"

test:
	echo "make test NOT IMPLEMENTED"

requirements:
	pip freeze > requirements.txt

docker-run:
	echo "make docker-run NOT IMPLEMENTED"

docker-build:
	echo "make docker-build NOT IMPLEMENTED"

docker-push:
	echo "make docker-push NOT IMPLEMENTED"
